[package]
name = "dtg-credentials"
description = "Decentralized Trust Graph (DTG) Credentials Library"
version = "0.2.0"
edition = "2024"
publish = true
authors = ["Glenn Gore <glenn@affinidi.com>"]
rust-version = "1.95.0"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/OpenVTC/dtg-credentials"

[features]
default = ["affinidi-signing"]
affinidi-signing = ["dep:affinidi-secrets-resolver"]

[dependencies]
affinidi-data-integrity = "0.7"
affinidi-secrets-resolver = { version = "0.5", optional = true }

chrono = "0.4"
multibase = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_json_canonicalizer = "0.3"
sha2 = "0.10"
thiserror = "2.0"
tracing = "0.1"

[dev-dependencies]
affinidi-tdk = "0.7"
anyhow = "1.0"
tokio = "1"
